variable "ami" {
    type = string
    description = "AMI to launch EC2 instance."
}

variable "subnet_id" {
    type = string
    description = "subnet id to launch EC2 instance in."
}

variable "instance_type" {
    type = string
    description = "type of compute instance."
    default = "t3.micro"
}

variable "name_prefix" {
    type = string
    description = "The prefix to apply to the beginning of names generated by this module."
}

variable "tags" {
    type = map(string)
    description = "Key/Value pairs to pass to AWS as Tags."
    default = {}
}

variable "instance_count" {
    type = number
    description = "The number of instances to launch."
    default = 0

    validation { 
    condition = can(parseint(tostring(var.my_integer), 10))
    error_message = "The instance count must be a whole number."
    }

    validation {
    condition = var.instance_count >= 0
    error_message = "The instance count can not be negative."
    }
}